package weave

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// Frozen packets generated by the original encoder at e300ddc, not by the
// implementation under test. Both video presets and partial blocks are covered.
func TestLegacyVideoPackets(t *testing.T) {
	fixture, err := os.ReadFile("testdata/wev1-e300ddc.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		PayloadSize int
		Data        []byte
		Packets     [][]byte
	}
	if err := json.Unmarshal(fixture, &cases); err != nil {
		t.Fatal(err)
	}
	for _, tc := range cases {
		cfg := Config{PayloadSize: tc.PayloadSize, DataFramesPerBlock: 16, RescueFramesPerBlock: 2}
		frames, err := Encode(tc.Data, cfg)
		if err != nil {
			t.Fatal(err)
		}
		frames = InterleaveByBlock(frames)
		if len(frames) != len(tc.Packets) {
			t.Fatal("frame count changed")
		}
		for i, frame := range frames {
			packet, err := frame.MarshalBinary()
			if err != nil || !bytes.Equal(packet, tc.Packets[i]) {
				t.Fatalf("WEV1 wire changed at %d: %v", i, err)
			}
		}
		for missing := uint32(0); missing <= 2; missing++ {
			var packets [][]byte
			for _, packet := range tc.Packets {
				frame, err := ParseFrame(packet)
				if err != nil {
					t.Fatal(err)
				}
				if frame.Header.FrameType == FrameTypeData && frame.Header.FrameIndex%16 < missing {
					continue
				}
				packets = append(packets, packet)
			}
			got, _, err := ReconstructBinary(packets, cfg)
			if err != nil || !bytes.Equal(got, tc.Data) {
				t.Fatalf("legacy recovery missing=%d capacity=%d: %v", missing, tc.PayloadSize, err)
			}
		}
	}
}

func TestVideoPayloadAboveStorageGroupLimit(t *testing.T) {
	// CHOP's 16 MiB group limit must not become a whole-video limit.
	want := coreData(17 << 20)
	cfg := Config{PayloadSize: 408, DataFramesPerBlock: 16, RescueFramesPerBlock: 2}
	frames, err := Encode(want, cfg)
	if err != nil {
		t.Fatal(err)
	}
	got, _, err := Reconstruct(frames[2:], cfg)
	if err != nil || !bytes.Equal(got, want) {
		t.Fatalf("large video recovery: %v", err)
	}
}

func TestReconstructFailurePreservesDestination(t *testing.T) {
	cfg := DefaultConfig()
	frames, err := Encode(coreData(5*cfg.PayloadSize), cfg)
	if err != nil {
		t.Fatal(err)
	}
	dst := bytes.Repeat([]byte{0xaa}, 6*cfg.PayloadSize)
	before := bytes.Clone(dst)
	if out, _, err := ReconstructTo(dst[:0], frames[3:], cfg); err == nil || out != nil {
		t.Fatal("unrecoverable input accepted")
	}
	if !bytes.Equal(dst, before) {
		t.Fatal("failed reconstruction modified destination")
	}
}

func TestTrailerValidation(t *testing.T) {
	path := filepath.Join(t.TempDir(), "video.mp4")
	for _, data := range [][]byte{nil, []byte("legacy gzip payload")} {
		if err := os.WriteFile(path, []byte("video"), 0600); err != nil {
			t.Fatal(err)
		}
		if _, found, err := ReadTrailer(path); found || err != nil {
			t.Fatal("false trailer detection", err)
		}
		if err := AppendTrailer(path, data); err != nil {
			t.Fatal(err)
		}
		got, found, err := ReadTrailer(path)
		if !found || err != nil || !bytes.Equal(got, data) {
			t.Fatal("trailer round trip", err)
		}
	}
	valid, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, length := range []uint64{^uint64(0), uint64(maxProtectedBytes) + 1, uint64(len(valid))} {
		bad := bytes.Clone(valid)
		binary.BigEndian.PutUint64(bad[len(bad)-trailerFooterSize:], length)
		if err := os.WriteFile(path, bad, 0600); err != nil {
			t.Fatal(err)
		}
		if out, found, err := ReadTrailer(path); !found || err == nil || out != nil {
			t.Fatal("invalid trailer length accepted")
		}
	}
	valid[5] ^= 1
	if err := os.WriteFile(path, valid, 0600); err != nil {
		t.Fatal(err)
	}
	if _, found, err := ReadTrailer(path); !found || err == nil {
		t.Fatal("corrupt trailer accepted")
	}
}
